[ENV_CONFIG]
scenario = vmas_dropout
agent = ia2c
n_agent = 4
; seed = 78
; seed = 12
; seed = 42
; seed = 123
; seed = 1212

; seed = 345
; seed = 789
; seed = 1001
; seed = 1010
; seed = 2021
; seed = 2020
; seed = 2022
; seed = 2023
; seed = 2024
; seed = 2025
seed = 2026

vmas_scenario = dropout
max_steps = 240
continuous_actions = False
device = cuda
coop_gamma = 0.9
use_gpu = True
num_envs = 1

[MODEL_CONFIG]
rmsp_alpha = 0.99
rmsp_epsilon = 1e-5
num_fc = 128
num_lstm = 128
lr_init = 1e-4
lr_decay = linear
value_coef = 1.0
gamma = 0.99
reward_clip = 10.0
batch_size = 60

#v_A
entropy_coef = 0.01
reward_norm = 0
lr_min = 1e-6
max_grad_norm = 5.0
#v_B
; entropy_coef = 0.03
; reward_norm = 1
; lr_min = 1e-5
; max_grad_norm = 5.0
; #v_C
; entropy_coef = 0.15
; reward_norm = 1
; lr_min = 1e-5
; max_grad_norm = 1.0

[TRAIN_CONFIG]
total_step = 1000000
test_interval = 5000
log_interval = 1000
save_interval = 10000

